document.addEventListener('DOMContentLoaded',()=>{
 if(!document.getElementById('fundoo-toggle-btn')){
  document.body.insertAdjacentHTML('beforeend','<div class="fundoo-widget-btn" id="fundoo-toggle-btn"><div class="fundoo-avatar"><img alt="" src="assets/favicon.svg"/></div><span>Fundoo</span></div><div class="fundoo-chat-panel" id="fundoo-panel"><div class="fundoo-header"><div style="display:flex;align-items:center;gap:10px"><div class="fundoo-avatar"><img alt="" src="assets/favicon.svg"/></div><div><h4 style="font-size:.9375rem;color:#fff;margin:0">Fundoo site guide</h4><span style="font-size:.6875rem;color:#1aa9e8;font-family:var(--font-mono)">Website navigation helper</span></div></div><button id="fundoo-close" aria-label="Close Fundoo" type="button">×</button></div><div class="fundoo-messages" id="fundoo-messages"><div class="msg-bubble msg-bot">Tell me which topic you are looking for. I can suggest pages from this website.</div></div><div class="fundoo-quick-prompts"><span class="quick-prompt-chip" data-prompt="Tell me about your services">Our services</span><span class="quick-prompt-chip" data-prompt="Tell me about your technology">Technology</span></div><div class="fundoo-input-area"><input id="fundoo-input" placeholder="Type your query..." type="text"/><button class="btn btn-accent btn-sm" id="fundoo-send" type="button">Send</button></div></div>');
 }
 const trigger=document.getElementById('fundoo-toggle-btn'),panel=document.getElementById('fundoo-panel'),input=document.getElementById('fundoo-input'),messages=document.getElementById('fundoo-messages');
 if(!trigger||!panel||!input||!messages)return;
 trigger.setAttribute('role','button');trigger.setAttribute('tabindex','0');trigger.setAttribute('aria-label','Open website guide');trigger.setAttribute('aria-expanded','false');
 panel.setAttribute('role','region');panel.setAttribute('aria-label','Website guide');messages.setAttribute('aria-live','polite');input.setAttribute('aria-label','Topic to find on this website');
 function setOpen(open){panel.classList.toggle('open',open);trigger.classList.toggle('collapsed',!open);trigger.setAttribute('aria-expanded',String(open));if(open){input.focus();}else trigger.focus();}
 trigger.addEventListener('click',()=>setOpen(!panel.classList.contains('open')));trigger.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setOpen(!panel.classList.contains('open'));}});document.getElementById('fundoo-close')?.addEventListener('click',()=>setOpen(false));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&panel.classList.contains('open'))setOpen(false);});
 setTimeout(()=>{if(!panel.classList.contains('open')) trigger.classList.add('collapsed');},5000);
 function append(text,user=false,links=[]){const item=document.createElement('div');item.className='msg-bubble '+(user?'msg-user':'msg-bot');item.textContent=text;for(const [label,url] of links){const a=document.createElement('a');a.href=url;a.textContent=label+' →';a.style.cssText='display:block;margin-top:10px;color:inherit;text-decoration:underline';item.append(a);}messages.append(item);messages.scrollTop=messages.scrollHeight;}
 function answer(q){const t=q.toLowerCase();if(/\basi\b|superintelligen|super intelligence/.test(t))return ['Artificial superintelligence (ASI) is a hypothetical form of AI exceeding human cognitive capabilities broadly. Our ASI page explains the concept, potential implications and open research questions; it does not describe a currently deployed ASI product.',[['Artificial Superintelligence (ASI)','si.html']]];if(/contact|email|enquir|book/.test(t))return ['Email solution@activebrains.co.uk to discuss your requirement. This guide cannot send a message or book an appointment.',[['Compose an email','mailto:solution@activebrains.co.uk']]];if(/price|cost|grant|fund|prize/.test(t))return ['This website does not publish fixed engagement prices or offer confirmed grants. Contact the team with your scope to discuss the relevant terms.',[['Contact ACTIVE BRAINS','mailto:solution@activebrains.co.uk']]];if(/launch|student|campus|university/.test(t))return ['Launch Pad explains how to frame an early idea or campus enquiry. Research covers the questions and evidence behind a potential experiment.',[['AB Launch Pad','launchpad.html'],['Research & Innovation','research.html']]];if(/coe|excellence/.test(t))return ['The CoE practice focuses on reusable standards, shared ownership and enablement for teams using common platforms.',[['Centre of Excellence','services-coe.html']]];if(/fabric|data|purview|analytic/.test(t))return ['These pages distinguish data engineering, analytical modelling and data governance.',[['Data & Analytics','data.html'],['Microsoft Fabric','tech-fabric.html'],['Microsoft Purview','tech-purview.html']]];if(/d365|crm|finance|microsoft/.test(t))return ['The Microsoft roadmap looks across the estate; the product pages address finance processes and customer-facing work separately.',[['Microsoft Platform Roadmap','tech-microsoft.html'],['Dynamics 365 Sales & Customer Service','tech-d365-crm.html'],['Dynamics 365 Finance & Operations','tech-d365-finance.html']]];if(/agent|ai|intelligen/.test(t))return ['Start with a bounded agent for one task, or explore orchestration when separate components need to coordinate.',[['AI & Autonomous Agents','service-ai-agents.html'],['Multi-Agent Workflow Orchestration','services-ai-agents.html']]];if(/cloud|aws|google/.test(t))return ['Compare platform choices or explore the migration and operating work behind a cloud environment.',[['Cloud Platform Selection','tech-aws-google.html'],['Cloud Services','service-cloud.html']]];if(/support|maintenance/.test(t))return ['Maintenance and managed operations have different scopes. These pages explain the distinction.',[['Continuous Support & AMC','service-continuous-support.html'],['Managed Application Operations','services-support.html']]];return ['I can help locate website topics, but I cannot answer questions beyond the published pages. Browse the complete directory or contact the team.',[['All pages','sitemap.html'],['Services directory','services.html']]];}
 function send(){const q=input.value.trim();if(!q)return;append(q,true);input.value='';const [text,links]=answer(q);append(text,false,links);}
 document.getElementById('fundoo-send')?.addEventListener('click',send);input.addEventListener('keydown',e=>{if(e.key==='Enter')send();});document.querySelectorAll('.quick-prompt-chip').forEach(chip=>{chip.setAttribute('role','button');chip.setAttribute('tabindex','0');function use(){input.value=chip.dataset.prompt||chip.textContent;send();}chip.addEventListener('click',use);chip.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();use();}});});
});
